name: Build and release cargo-shuttle
on: workflow_dispatch
  # schedule:
    # - cron: '38 5 * * *'
jobs:
  versions:
    name: Check whether build is necessary
    runs-on: ubuntu-latest
    outputs:
      upstream_version: ${{ steps.versions.outputs.upstream_version }}
      local_version: ${{ steps.versions.outputs.local_version }}
    steps:
      - id: versions
        name: Query Github API for latest versions
        run: |
          UPSTREAM_VERSION=$(curl -fsSL https://api.github.com/repos/shuttle-hq/shuttle/releases | jq -r '.[0].tag_name')
          echo "upstream_version=$UPSTREAM_VERSION" >> $GITHUB_OUTPUT
          LOCAL_VERSION=$(curl -fsSL https://api.github.com/repos/jfmontanaro/cargo-shuttle-builds/releases | jq -r '.[0].tag_name')
          if [[ $LOCAL_VERSION == $UPSTREAM_VERSION ]]; then
            echo "Update not needed: $LOCAL_VERSION == $UPSTREAM_VERSION"
          else
            echo "Update needed: $LOCAL_VERSION => $UPSTREAM_VERSION"
          fi

  build:
    name: Build Shuttle
    needs: versions
    if: needs.versions.outputs.upstream_version != needs.versions.outputs.local_version
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - os: ubuntu
            filename: cargo-shuttle
          - os: windows
            filename: cargo-shuttle.exe
          - os: macos
            filename: cargo-shuttle
    steps:
      - id: checkout
        name: Checkout Shuttle repository
        uses: actions/checkout@v3
        with:
          repository: shuttle-hq/shuttle

      - name: Install pkg-config
        if: matrix.os == 'ubuntu'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y pkg-config

      - name: Build cargo-shuttle
        run: cargo build -p cargo-shuttle --release

      - id: upload-artifact
        name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: cargo-shuttle-${{ matrix.os }}
          path: target/release/${{ matrix.filename }}
